# Generated by Django 4.2.4 on 2023-08-29 14:11

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to=pathlib.PureWindowsPath('C:/MyFiles/Python/django-todo/backend/media')),
        ),
    ]
